environment:
  APPVEYOR_BUILD_WORKER_CLOUD: pro-lw

install:
  - ps: >-
      $env:JAVA_HOME = "C:\Program Files (x86)\Java\jdk1.8.0"
      $env:PATH = "$env:JAVA_HOME\bin;C:\Program Files (x86)\Java\jre8\bin\client;$env:PATH"
      [Environment]::SetEnvironmentVariable("JAVA_HOME", $env:JAVA_HOME, [EnvironmentVariableTarget]::Machine)
      [Environment]::SetEnvironmentVariable("Path", $env:PATH, [EnvironmentVariableTarget]::Machine)
      npm i

build_script:
  - npm run screenshot